config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  get "/update_check", to: "rooms#update_check"
  get "/show_additionally", to: "rooms#show_additionally"
  get '/search', to: 'rooms#search'

  resources :rooms, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  namespace :api, { format: 'json' } do
    resources :emojis, only: :index
  end

  mount ActionCable.server => "/cable"

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users
  has_many :messages
  validates :name, presence: true, length: { maximum: 50 }

  # roomの中にメッセージを投稿しているユーザーを取得
  def users_of_messages
    User.joins(:messages).where(messages: { room_id: id }).distinct
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all.order("id DESC")
  end

  def new
    @room = Room.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @room = Room.new(room_params)
    @rooms = Room.all.order("id DESC")
    respond_to do |format|
      if @room.save
        format.html { redirect_to root_path }
        format.js
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.includes(:user).order(:id).last(10)
    # @room内のchecksをすべて削除する
    current_user.delete_checks_in(@room)
    # @roomの最新のメッセージをcheckする
    if latest_message = @room.messages.where.not(user_id: current_user.id).order(:id).last # rubocop:disable Lint/AssignmentInCondition
      current_user.checks.create(message_id: latest_message.id)
    end
  end

  def update_check
    @room = Room.find(params[:id])
    # @room内のchecksをすべて削除する
    current_user.delete_checks_in(@room)
    # @roomの最新のメッセージをcheckする
    if latest_message = @room.messages.where.not(user_id: current_user.id).order(:id).last # rubocop:disable Lint/AssignmentInCondition
      current_user.checks.create(message_id: latest_message.id)
    end
    last_id = params[:oldest_message_id].to_i
    latest_id = params[:latest_message_id].to_i
    @messages = @room.messages.includes(:user).order(:id).where(id: last_id..latest_id)
    render partial: 'new_messages', locals: { messages: @messages }
  end

  def show_additionally
    @room = Room.find(params[:id])
    last_id = params[:oldest_message_id].to_i - 1
    @messages = @room.messages.includes(:user).order(:id).where(id: 1..last_id).last(5)
    render partial: 'new_messages', locals: { messages: @messages }
  end

  def search
    if params[:room][:id].blank?
      @searched_area = "全てのチャットルーム"
    else
      if searched_area = Room.find(params[:room][:id]) # rubocop:disable Lint/AssignmentInCondition
        @searched_area = searched_area.name
      else
        redirect_to request.referrer || root_url
      end
    end

    if params[:room][:search].blank?
      @searched_word = "検索ワードが入力されていません"
      @messages = Message.none
    else
      @searched_word = params[:room][:search]
      searched_messages = Message.search(params[:room][:search], params[:room][:id])
      if searched_messages.any?
        @messages = searched_messages
      else
        @messages = Message.none
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def room_params
    params.require(:room).permit(:name).merge(user_ids: current_user.id)
  end
end

app/views/rooms/_index.html.erb
<%= render rooms %>

app/views/rooms/_new_messages.html.erb
<%= render messages %>

app/views/rooms/_new_room.html.erb
<%= form_with(class: "new_room_form", model: room, remote: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object, room: room %>

  <%= f.label :チャットルーム名 %><br />
  <p><%= f.text_field :name %></p>
  <p><%= f.submit "チャットルームの作成" %><p>
<% end %>

app/views/rooms/_room.html.erb
<li class="room_list <%= room.id %>">
  <%= link_to "#{room.name}", room_path(room), class:"family_button" %>
  <p class="room_users">
    このチャットルームの参加者
    <% room.users_of_messages.each do |user| %>
      /<%= user.name %> 
    <% end %>
  </p>
</li>

app/views/rooms/_searched_messages.html.erb
<% messages.includes([:room, :user]).each do |message| %>
  <div class="searched-message">
    <div class="searched-room">
      チャットルーム名：<%= message.room.name%>
    </div>
    <li class="message <%= "self" if message.user_id == current_user.id %>" id="message-<%= message.id %>">
      <div class="message_user_name">
        <%= message.user.name %>：
        <%= message.created_at.strftime('%Y/%m/%d %H:%M') %>
      </div>
      <div class="message_content result">
        <%= simple_format(emojify(h message.content)) %>
      </div>
    </li>
  </div>
<% end %>

app/views/rooms/_searched_modal.html.erb
<div class="close-modal">
  <i class="fa fa-2x fa-times"></i>
</div>

<div class="modal-content">
  <%= render 'searched_title', searched_word: @searched_word, searched_area: @searched_area %>
  <%= render 'searched_messages', messages: @messages %>
</div>

app/views/rooms/_searched_title.html.erb
<div class="searched-title">
  <div>
    （検索結果）
  </div>
  <div>
    検索ワード：<span id="keyword"><%= emojify(searched_word) %></span>
  </div>
  <div>
    検索対象のチャットルーム：<%= searched_area %>
  </div>
</div>

app/views/rooms/_updated_rooms.html.erb
<%= render rooms %>

app/views/rooms/create.js.erb
$('#rooms').html("<%= escape_javascript(render partial: 'updated_rooms', locals: { rooms: @rooms }) %>");
$('#room-form').fadeOut();

app/views/rooms/index.html.erb
<h4 class="myaccount"><%= link_to 'マイアカウント', edit_user_registration_path %></h4>
<h2>チャットルーム一覧</h2>

<%= link_to "チャットルームを作成する", new_room_path, remote: true,
                        class: "btn btn-primary chat_room_btn" %>
<div id="room-form"></div>

<ul class="room_lists" id="rooms">
  <%= render @rooms %>
</ul>

app/views/rooms/new.html.erb
<%= render "new_room", room: @room %>

app/views/rooms/new.js.erb
$('#room-form').html("<%= escape_javascript(render partial: 'room_form', locals: { room: @room }) %>");
$('#room-form').fadeIn();

app/views/rooms/search.js.erb
$('#searched-modal').html("<%= escape_javascript(render partial: 'searched_modal', locals: {
  searched_area: @searched_area,
  messages: @messages,
  searched_word: @searched_word
  }) %>");
$('#searched-modal').fadeIn();

var keyword = $("#keyword").text();
$(".result").highlight(keyword);

app/views/rooms/show_additionally.html.erb
$('#messages').prepend("<%= escape_javascript(render partial: 'add_messages', locals: { messages: @messages }) %>");
$('#result').text('');