config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  get "/update_check", to: "rooms#update_check"
  get "/show_additionally", to: "rooms#show_additionally"
  get '/search', to: 'rooms#search'

  resources :rooms, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end

  namespace :api, { format: 'json' } do
    resources :emojis, only: :index
  end

  mount ActionCable.server => "/cable"

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end
end

app/views/layouts/_footer.html.erb
<footer class="sticky-bottom bg-primary">
</footer>

app/views/layouts/_header.html.erb
<header class="bg-primary">
  <div class="container">
    <nav>
      <div class="header-title">
        <% if room.present? %>
          <%= link_to rooms_path do %>
            <span class= "fa fa-3x fa-angle-left"></span>
          <% end %>
          チャットルーム名：<%= room.name %>
        <% else %>
          チャットアプリ
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= render 'shared/search_form', room: room %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" cotent="width=device-width,initial-scale=1">
<%= stylesheet_link_tag 'application', media: 'all' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header', room: @room %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>